### ISSUE TITLE
Script execution is prohibited

### ISSUE THREAD

**Issue by Thomas1664** [apache/cordova-js#212]
When I try to debug my project with VS Code I get following error: [cordova-tools] Error processing "launch": Script execution is prohibited

Output from debug-console:

Attaching to app
An error occurred while attaching to the debugger. Script execution is prohibited
Script execution is prohibitedError processing "launch": Error: Script execution is prohibited
    at Client.processMessage (c:\Users\thhei\.vscode\extensions\msjsdiag.cordova-tools-1.8.6\node_modules\noice-json-rpc\lib\noice-json-rpc.js:66:36)
    at LoggingSocket.Client.socket.on (c:\Users\thhei\.vscode\extensions\msjsdiag.cordova-tools-1.8.6\node_modules\noice-json-rpc\lib\noice-json-rpc.js:42:48)
    at LoggingSocket.emit (events.js:187:15)
    at Receiver.receiverOnMessage (c:\Users\thhei\.vscode\extensions\msjsdiag.cordova-tools-1.8.6\node_modules\ws\lib\websocket.js:744:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (c:\Users\thhei\.vscode\extensions\msjsdiag.cordova-tools-1.8.6\node_modules\ws\lib\receiver.js:417:14)
    at perMessageDeflate.decompress (c:\Users\thhei\.vscode\extensions\msjsdiag.cordova-tools-1.8.6\node_modules\ws\lib\receiver.js:374:23)
    at _decompress (c:\Users\thhei\.vscode\extensions\msjsdiag.cordova-tools-1.8.6\node_modules\ws\lib\permessage-deflate.js:298:9)
    at _inflate.flush (c:\Users\thhei\.vscode\extensions\msjsdiag.cordova-tools-1.8.6\node_modules\ws\lib\permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:480:3)

### Command or Code
Debugging: Simulate Android in browser

### Version information

OS: Windows 10 Home Version 1903
IDE: VS Code
cordova version: 9.0.0 (cordova-lib@9.0.1)
Plugins: none
Chrome: 77.0.3865.90

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by raphinesse** [comment]
I think you should try to solve that issue with the authors of the VSCode extension you are using (`msjsdiag.cordova-tools-1.8.6`). We can't provide support for that extension and I'm afraid we can't help you with your problem. If it turns out that this is actually a bug in `cordova-js`, feel free to provide more details here.
